### ISSUE TITLE
Compilation Error with GTest 1.11.0 Lib

### ISSUE THREAD

**Issue by surajmitsel** [google/googletest#3551] opened 2021-09-02 11:57 UTC
**Describe the bug**

I am using already GTest lib 1.10 version in my project which compiles and runs well,
So i upgraded the GTest lib with 1.11 version (commit id : e2239ee6043f73722e7aa812a459f54a28552929) 
and started getting the below compilation errors

Log """
from /home/parstream-ci.gen/workspace/onents_EDGE-6614_GTestLib_update/lib-eip/unit-test/test_device_eip.cpp:1:

/arm-linux-musleabihf-cross/arm-linux-musleabihf/include/c++/10.2.1/ostream:773:5: note: candidate: ‘template<class _Ostream, class _Tp> typename std::enable_if<std::__and_<std::__not_<std::is_lvalue_reference<_Tp> >, std::__is_convertible_to_basic_ostream<_Ostream>, std::__is_insertable<typename std::__is_convertible_to_basic_ostream<_Tp>::__ostream_type, const _Tp&, void> >::value, typename std::__is_convertible_to_basic_ostream<_Tp>::__ostream_type>::type std::operator<<(_Ostream&&, const _Tp&)’

  773 |     operator<<(_Ostream&& __os, const _Tp& __x)

      |     ^~~~~~~~

/arm-linux-musleabihf-cross/arm-linux-musleabihf/include/c++/10.2.1/ostream:773:5: note:   template argument deduction/substitution failed:

/arm-linux-musleabihf-cross/arm-linux-musleabihf/include/c++/10.2.1/ostream: In substitution of ‘template<class _Ostream, class _Tp> typename std::enable_if<std::__and_<std::__not_<std::is_lvalue_reference<_Tp> >, std::__is_convertible_to_basic_ostream<_Ostream>, std::__is_insertable<typename std::__is_convertible_to_basic_ostream<_Tp>::__ostream_type, const _Tp&, void> >::value, typename std::__is_convertible_to_basic_ostream<_Tp>::__ostream_type>::type std::operator<<(_Ostream&&, const _Tp&) [with _Ostream = std::basic_ostream<char>&; _Tp = common::DeviceStatus::AccessType]’:

/usr/local/include/gtest/gtest-printers.h:287:8:   recursively required from ‘struct testing::internal::FindFirstPrinter<common::DeviceStatus::AccessType, void, testing::internal::FunctionPointerPrinter, testing::internal::PointerPrinter, testing::internal::internal_stream_operator_without_lexical_name_lookup::StreamPrinter, testing::internal::ProtobufPrinter, testing::internal::ConvertibleToIntegerPrinter, testing::internal::ConvertibleToStringViewPrinter, testing::internal::RawBytesPrinter, testing::internal::FallbackPrinter>’

/usr/local/include/gtest/gtest-printers.h:287:8:   required from ‘struct testing::internal::FindFirstPrinter<common::DeviceStatus::AccessType, void, testing::internal::ContainerPrinter, testing::internal::FunctionPointerPrinter, testing::internal::PointerPrinter, testing::internal::internal_stream_operator_without_lexical_name_lookup::StreamPrinter, testing::internal::ProtobufPrinter, testing::internal::ConvertibleToIntegerPrinter, testing::internal::ConvertibleToStringViewPrinter, testing::internal::RawBytesPrinter, 
"""

 **Does the bug persist in the most recent commit?**
Its in GTEst 1.11.0 

We recommend using the latest commit in the master branch in your projects.

**What operating system and version are you using?**
Distributor ID: Ubuntu
Description:    Ubuntu 20.04.3 LTS
Release:        20.04
Codename:       focal

**What compiler and version are you using?**
Using built-in specs.
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/usr/lib/gcc/x86_64-linux-gnu/9/lto-wrapper
OFFLOAD_TARGET_NAMES=nvptx-none:hsa
OFFLOAD_TARGET_DEFAULT=1
Target: x86_64-linux-gnu
Configured with: ../src/configure -v --with-pkgversion='Ubuntu 9.3.0-17ubuntu1~20.04' --with-bugurl=file:///usr/share/doc/gcc-9/README.Bugs --enable-languages=c,ada,c++,go,brig,d,fortran,objc,obj-c++,gm2 --prefix=/usr --with-gcc-major-version-only --program-suffix=-9 --program-prefix=x86_64-linux-gnu- --enable-shared --enable-linker-build-id --libexecdir=/usr/lib --without-included-gettext --enable-threads=posix --libdir=/usr/lib --enable-nls --enable-clocale=gnu --enable-libstdcxx-debug --enable-libstdcxx-time=yes --with-default-libstdcxx-abi=new --enable-gnu-unique-object --disable-vtable-verify --enable-plugin --enable-default-pie --with-system-zlib --with-target-system-zlib=auto --enable-objc-gc=auto --enable-multiarch --disable-werror --with-arch-32=i686 --with-abi=m64 --with-multilib-list=m32,m64,mx32 --enable-multilib --with-tune=generic --enable-offload-targets=nvptx-none=/build/gcc-9-HskZEa/gcc-9-9.3.0/debian/tmp-nvptx/usr,hsa --without-cuda-driver --enable-checking=release --build=x86_64-linux-gnu --host=x86_64-linux-gnu --target=x86_64-linux-gnu
Thread model: posix
gcc version 9.3.0 (Ubuntu 9.3.0-17ubuntu1~20.04) 

**What build system are you using?**
x86_64-linux-gnu

cmake version 3.21.2

**Additional context**

i am using C++17 lib ..So please let me know if any lib i need to upgrade to use GTest [1.11]

**Comment by derekmauro** [comment] 2021-09-13 19:46
Closing because no example code was provided. Please re-open this issue with code that reproduces the issue.

**Closed by derekmauro** 2021-09-13 19:46 UTC
Labels: bug
