### ISSUE TITLE
Gmock options can not be set from environment

### ISSUE THREAD

**Issue by Bu11etmagnet** [google/googletest#1638] opened 2018-06-21 08:50 UTC
Contrary to gtest options (e.g. gtest_filter), gmock options can not be set from the environment. Setting GMOCK_VERBOSE=info has no effect.

This happens because gmock options are defined with fixed defaults:
```
GMOCK_DEFINE_string_(verbose, internal::kWarningVerbosity,
                     "Controls how verbose Google Mock's output is."
                     "  Valid values:\n"
                     "  info    - prints all messages.\n"
                     "  warning - prints warnings and errors.\n"
                     "  error   - prints errors only.");
```
as opposed to gtest options, which are defined with default values that check the environment:
```
GTEST_DEFINE_string_(
    color,
    internal::StringFromGTestEnv("color", "auto"),
    "Whether to use colors in the output.  Valid values: yes, no, "
    "and auto.  'auto' means to use colors if the output is "
    "being sent to a terminal and the TERM environment variable "
    "is set to a terminal type that supports colors.");
```

The default value in `GMOCK_DEFINE_string_(verbose ...)` should be a call to `StringFromGTestEnv`

**Comment by gennadiycivil** [comment] 2018-12-28 20:36
Thank you very much for this report. The best way to approach this would be to create a proper PR and submit it for consideration.

**Comment by gennadiycivil** [comment] 2018-12-28 20:47
Duplicate of https://github.com/google/googletest/issues/1356

**Comment by CJ-Johnson** [comment] 2020-06-09 15:40
Closing due to inactivity. Please reopen if this still a concern.

**Closed by CJ-Johnson** 2020-06-09 15:40 UTC
Labels: GC Attention Set
