### ISSUE TITLE
Gmock MOCK_METHOD improvement

### ISSUE THREAD

**Issue by fmanea** [google/googletest#1330] opened 2017-11-16 15:12 UTC
Idea for an Improvement: MOCK_METHOD macro doesn't use "override" functionality from C++11, and if you have a pure virtual class from which you inherit, and somehow, the parameters inside MOCK_METHOD are not the same from the class you want to mock=> if try to instantiate this mock, you will get misleading  errors, about pure virtual class not able to be instantiated. That's because Mock_method doesn't ensure that the method from the base class exists with that definition, and if other parameters are added, it simply creates that method. So, I guess that c++11 "override" functionality could be used in this case, but this implies other things (it forces users to use c++11). It's just an idea for improvement.

**Comment by AbigailBuccaneer** [comment] 2017-12-04 15:07
Duplicate of #533

**Comment by gennadiycivil** [comment] 2019-08-02 20:00
With new MOCK_METHOD I belive this is not an issue anymore

**Closed by gennadiycivil** 2019-08-02 20:00 UTC
