### ISSUE TITLE
GTEST_SKIP() release

### ISSUE THREAD

**Issue by bilelzouari** [google/googletest#2343] opened 2019-07-24 16:07 UTC
Hi will there be a release for a version containing GTEST_SKIP() and skipped in xml compatible with JUNIT standard xsd

**Comment by ocroquette** [comment] 2019-07-30 20:21
See also https://github.com/google/googletest/issues/2267

**Comment by gennadiycivil** [comment] 2019-08-02 18:40
Duplicate of #2267

**Closed by gennadiycivil** 2019-08-02 18:40 UTC
