### ISSUE TITLE
ASSERT_EQ segfault with two boost::filesystem::path

### ISSUE THREAD

**Issue by graywolf** [google/googletest#1614] opened 2018-05-26 09:02 UTC
ASSERT_EQ segfaults while trying to print in case of not equal if you use two instances for boost::filesystem::path. Minimal example:

```
TEST(a, b) {
    ASSERT_EQ(boost::filesystem::path("a"), boost::filesystem::path("b"));
}
```

when ran under gdb gives you:

```
Program received signal SIGSEGV, Segmentation fault.
0x00007ffff68f50e4 in std::__ostream_insert<char, std::char_traits<char> > (__out=..., __s=__s@entry=0x7fffff7ff06c "{", __n=__n@entry=1)
    at /build/gcc/src/gcc-build/x86_64-pc-linux-gnu/libstdc++-v3/include/bits/ostream_insert.h:76
76	/build/gcc/src/gcc-build/x86_64-pc-linux-gnu/libstdc++-v3/include/bits/ostream_insert.h: No such file or directory.
```

Stacktrace is 116468 levels deep, so attached as attachement (25MB): 
[gdb.txt](https://github.com/google/googletest/files/2041453/gdb.txt)

**Comment by pepsiman** [comment] 2018-06-01 09:13
Duplicate of #521.

**Comment by graywolf** [comment] 2018-06-03 19:50
I would think so, but the fix was merged into master and yet this still happend to me. So maybe the fix is not complete?

**Comment by graywolf** [comment] 2018-06-03 19:51
Anyway #521 is still open, why? Wasn't https://github.com/google/googletest/pull/1186 supposed to fix it?

**Comment by ixSci** [comment] 2018-06-07 13:10
This issue is not duplicate because the original issue was fixed (I don't understand why you didn't close #521 ?). Then in this [commit](https://github.com/google/googletest/commit/a3c2e107aeb7e821b76164cea366094ce420b656) the issue was brought up again but with different cause. In the aforementioned commit the following code has been added:
`template<typename T>
struct VoidT {
    typedef void value_type;
};

template <typename T, typename = void>
struct HasValueType : false_type {};
template <typename T>
struct HasValueType<T, VoidT<typename T::value_type> > : true_type {
};
`
Which is totally wrong. I do not know why it was added in the first place, but at least making it working it should look like this:
`template<typename T>
struct Void {
    typedef void type;
};

template<typename T>
using VoidT = typename Void<T>::type;

template <typename T, typename = void>
struct HasValueType: false_type {};
template <typename T>
struct HasValueType<T, VoidT<typename T::value_type>>: true_type {
};`

Otherwise the `IsRecursiveContainer` trait will always return false which breaks `std::filesystem::path` usage in GTest.

**Comment by rleigh-codelibre** [comment] 2018-10-31 19:28
Occurs for me with both `std::filesystem::path` and `boost::filesystem::path`.

**Comment by dvetutnev** [comment] 2018-12-04 16:05
> Otherwise the `IsRecursiveContainer` trait will always return false which breaks `std::filesystem::path` usage in GTest (the same goes to boost::fs).

Work with boost::filesystem::path (1.68.0) on GCC 6.3 and MSVC 14.16.27023

**Comment by rleigh-codelibre** [comment] 2018-12-05 10:15
I've retested with current `master` (fe14e30307) and GCC 8.2 on Linux with `-std=gnu++17`.  It's still segfaulting here.

**Comment by gennadiycivil** [comment] 2018-12-05 15:55
@rleigh-codelibre , @GTValentine , @dvetutnev , @ixSci , @graywolf 
Thank you very much for this discussion. The best way to approach this would be to create a proper PR and submit it for consideration. In addition proper unit test would ensure that this wont happen again. There should be enough expertise in this discussion for this to happen.
Thanks again

**Comment by gennadiycivil** [comment] 2018-12-27 21:47
Should be good now

**Closed by gennadiycivil** 2018-12-27 21:47 UTC

**Comment by Kittyfisto** [comment] 2019-09-18 09:05
Are there any plans to do a proper release with these fixes?
