### ISSUE TITLE
Visual Studio 2017, c++17, error C3083: 'tr1': the symbol to the left of a '::' must be a type 

### ISSUE THREAD

**Issue by coder0xff** [google/googletest#1138] opened 2017-07-02 04:18 UTC
When I build a test project in a Visual Studio 2017 with the `Properties > C/C++ > Language > C++ Language Standard` set to `/std:c++lastest`, I get build errors in gtest-port.h and gtest-printers.h. It works fine when set to `/std:c++14`. Here is the full build output:

```
1>------ Build started: Project: parlex_test, Configuration: Debug Win32 ------
1>test.cpp
1>C:\Users\Brent\Desktop\plange.build\Dependencies\googletest\include\gtest/internal/gtest-port.h(1031): error C2039: 'tr1': is not a member of 'std'
1>C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\VC\Tools\MSVC\14.10.25017\include\sstream(13): note: see declaration of 'std'
1>C:\Users\Brent\Desktop\plange.build\Dependencies\googletest\include\gtest/internal/gtest-port.h(1031): error C3083: 'tr1': the symbol to the left of a '::' must be a type
1>C:\Users\Brent\Desktop\plange.build\Dependencies\googletest\include\gtest/internal/gtest-port.h(1032): error C2039: 'tr1': is not a member of 'std'
1>C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\VC\Tools\MSVC\14.10.25017\include\sstream(13): note: see declaration of 'std'
1>C:\Users\Brent\Desktop\plange.build\Dependencies\googletest\include\gtest/internal/gtest-port.h(1032): error C3083: 'tr1': the symbol to the left of a '::' must be a type
1>C:\Users\Brent\Desktop\plange.build\Dependencies\googletest\include\gtest/internal/gtest-port.h(1033): error C2039: 'tr1': is not a member of 'std'
1>C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\VC\Tools\MSVC\14.10.25017\include\sstream(13): note: see declaration of 'std'
1>C:\Users\Brent\Desktop\plange.build\Dependencies\googletest\include\gtest/internal/gtest-port.h(1033): error C3083: 'tr1': the symbol to the left of a '::' must be a type
1>C:\Users\Brent\Desktop\plange.build\Dependencies\googletest\include\gtest/internal/gtest-port.h(1034): error C2039: 'tr1': is not a member of 'std'
1>C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\VC\Tools\MSVC\14.10.25017\include\sstream(13): note: see declaration of 'std'
1>C:\Users\Brent\Desktop\plange.build\Dependencies\googletest\include\gtest/internal/gtest-port.h(1034): error C3083: 'tr1': the symbol to the left of a '::' must be a type
1>C:\Users\Brent\Desktop\plange.build\Dependencies\googletest\include\gtest/internal/gtest-port.h(1035): error C2039: 'tr1': is not a member of 'std'
1>C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\VC\Tools\MSVC\14.10.25017\include\sstream(13): note: see declaration of 'std'
1>C:\Users\Brent\Desktop\plange.build\Dependencies\googletest\include\gtest/internal/gtest-port.h(1035): error C3083: 'tr1': the symbol to the left of a '::' must be a type
1>C:\Users\Brent\Desktop\plange.build\Dependencies\googletest\include\gtest/gtest-printers.h(613): error C2039: 'tr1': is not a member of 'std'
1>C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\VC\Tools\MSVC\14.10.25017\include\iterator(15): note: see declaration of 'std'
1>C:\Users\Brent\Desktop\plange.build\Dependencies\googletest\include\gtest/gtest-printers.h(613): error C3083: 'tr1': the symbol to the left of a '::' must be a type
1>C:\Users\Brent\Desktop\plange.build\Dependencies\googletest\include\gtest/gtest-printers.h(618): error C3083: 'tr1': the symbol to the left of a '::' must be a type
1>C:\Users\Brent\Desktop\plange.build\Dependencies\googletest\include\gtest/gtest-printers.h(623): error C3083: 'tr1': the symbol to the left of a '::' must be a type
1>C:\Users\Brent\Desktop\plange.build\Dependencies\googletest\include\gtest/gtest-printers.h(628): error C3083: 'tr1': the symbol to the left of a '::' must be a type
1>C:\Users\Brent\Desktop\plange.build\Dependencies\googletest\include\gtest/gtest-printers.h(633): error C3083: 'tr1': the symbol to the left of a '::' must be a type
1>C:\Users\Brent\Desktop\plange.build\Dependencies\googletest\include\gtest/gtest-printers.h(638): error C3083: 'tr1': the symbol to the left of a '::' must be a type
1>C:\Users\Brent\Desktop\plange.build\Dependencies\googletest\include\gtest/gtest-printers.h(645): error C3083: 'tr1': the symbol to the left of a '::' must be a type
1>C:\Users\Brent\Desktop\plange.build\Dependencies\googletest\include\gtest/gtest-printers.h(652): error C3083: 'tr1': the symbol to the left of a '::' must be a type
1>C:\Users\Brent\Desktop\plange.build\Dependencies\googletest\include\gtest/gtest-printers.h(659): error C3083: 'tr1': the symbol to the left of a '::' must be a type
1>C:\Users\Brent\Desktop\plange.build\Dependencies\googletest\include\gtest/gtest-printers.h(666): error C3083: 'tr1': the symbol to the left of a '::' must be a type
1>C:\Users\Brent\Desktop\plange.build\Dependencies\googletest\include\gtest/gtest-printers.h(674): error C3083: 'tr1': the symbol to the left of a '::' must be a type
1>C:\Users\Brent\Desktop\plange.build\Dependencies\googletest\include\gtest/gtest-printers.h(891): error C3083: 'tr1': the symbol to the left of a '::' must be a type
1>C:\Users\Brent\Desktop\plange.build\Dependencies\googletest\include\gtest/gtest-printers.h(891): note: see reference to class template instantiation 'testing::internal::TuplePolicy<TupleT>::tuple_element<I>' being compiled
1>C:\Users\Brent\Desktop\plange.build\Dependencies\googletest\include\gtest/gtest-printers.h(899): note: see reference to class template instantiation 'testing::internal::TuplePolicy<TupleT>' being compiled
1>C:\Users\Brent\Desktop\plange.build\Dependencies\googletest\include\gtest/gtest-printers.h(895): error C3083: 'tr1': the symbol to the left of a '::' must be a type
1>Done building project "parlex_test.vcxproj" -- FAILED.
========== Build: 0 succeeded, 1 failed, 3 up-to-date, 0 skipped ==========

```

**Comment by KindDragon** [comment] 2017-07-02 11:11
Duplicate of #1111

**Comment by KindDragon** [comment] 2017-10-25 16:14
Can be closed. PR #1218 fixed this

**Closed** 2017-10-25 20:42 UTC
