### ISSUE TITLE
Test fail due to SEGFAULT using GNU 9.3.0

### ISSUE THREAD

**Issue by langroodi** [google/googletest#3506] opened 2021-07-31 12:41 UTC
I have added a new test to [my project](https://github.com/langroodi/Adaptive-AUTOSAR/) as follows which caused a segmentation fault while running 'ctest' command:

        TEST(LoggingFrameworkTest, LogMethod)
        {
            const std::string cAppId{"APP01"};
            const LogMode cLogMode{LogMode::kConsole};
            const std::string cCtxId{"CTX01"};
            const std::string cCtxDescription{"Default Test Context"};
            const LogLevel cLogLevel{LogLevel::kWarn};

            LoggingFramework _loggingFramework =
                LoggingFramework::Create(cAppId, cLogMode); // Calling static factory pattern function

           Logger _logger =
                _loggingFramework.CreateLogger(cCtxId, cCtxDescription);
            
            LogStream _logStream;

            ASSERT_NO_THROW(
                _loggingFramework.Log(_logger, cLogLevel, _logStream));
        }

at this part of the code:

        LoggingFramework LoggingFramework::Create(
            std::string appId,
            LogMode logMode,
            LogLevel logLevel,
            std::string appDescription)
        {
            if (logMode == LogMode::kFile)
            {
                throw std::invalid_argument(
                    "File logging mode is not feasible within this constructor override.");
            }

            if (logMode == LogMode::kConsole)
            {
                sink::LogSink *_logSink =
                    new sink::ConsoleLogSink(appId, appDescription);
                LoggingFramework _result(_logSink, logLevel); // <-- Error occurs here

                return _result;
            }
            else
            {
                throw std::invalid_argument(
                    "The log mode is not currently supported.");
            }
        }

The code has been compiled in the Debug mode via **GCC 9.3.0 x86-64 Linux-GNU**. I even disabled the PTHREADS using _gtest_disable_pthreads_ option, but it did not solve the issue. Following is the link to my CMakeLists:
https://github.com/langroodi/Adaptive-AUTOSAR/blob/master/CMakeLists.txt

When I changed the compiler type in my pipeline from GCC to **Clang 10.0** the issue disappeared. The whole project build workspace is generated by CMake 3.16.

I am still using this commit: 
8d51ffdfab10b3fba636ae69bc03da4b54f8c235
of Google Test without using any object mocking. So, I am not sure the issue is solved in the newer commit or not. Or maybe there is a error in my code.

If you need more information, I would be happy to provide that.

**Comment by asoffer** [comment] 2021-08-02 19:37
Without seeing the constructor for the `LoggingFramework` object or the stack trace from the segfault we will not be able to help here. Could you produce a [Compiler Explorer](https://godbolt.org/) link reproducing the issue?

**Comment by Anucha7736zxc** [comment] 2021-08-03 16:20
https://member.ufa2899.com/register/

**Comment by asoffer** [comment] 2021-08-09 19:44
The segfault seems to be in the Log member function, which is only passed objects constructed that are not related to googletest, making me think it's likely unrelated to googletest. Given that, I'm going to close this. If you find evidence that the crash is related to googletest, please reopen.

Runing the code with something like Address Sanitizer might be instructive.

**Closed by asoffer** 2021-08-09 19:44 UTC
Labels: bug, More Information Requested
