### ISSUE TITLE
`clock_gettime` with `CLOCK_REALTIME` not working - timeout definition for `mq_timedreceive`

### ISSUE THREAD

**Issue by JanFeld** [google/googletest#3539] opened 2021-08-26 07:26 UTC
**Describe the bug**

When testing functions of a class which contains some POSIX-Queue functions which require `mq_timedreceive` this timeout will never be reached.
Requirement for timeouts to occur in `mq_timedreceive` is an absolute time specification (`struct timespec`) based on `clock_gettime(CLOCK_REALTIME, ..)` with a positive offset.

I'm running tests which are starting a thread during `SetUp` using this function.
On `TearDown` this thread will be stopped and joined.
Due to the missing timeout it hangs forever and the tests won't run.
When running the application `mq_timedreceive` timeouts work.

The tests don't use the timedreceive internally but the class is starting the thread.
If the thread will not be joined the test fails with an exception.
If timeouts for tests are set to prevent deadlocks the tests fail due to the timeout. (ctest)

---

**Steps to reproduce the bug**

Use a POSIX-style message queue interface and calls to `mq_timedreceive`.
The function won't return.

---

**Does the bug persist in the most recent commit?**

Yes.

---

**What operating system and version are you using?**
Debian Sid (Unstable), 5.10.46-4

---

**What compiler and version are you using?**

g++ (Debian 10.3.0-7) 10.3.0

---

**What build system are you using?**
cmake version 3.18.4

---

Regards,
Jan

**Comment by derekmauro** [comment] 2021-08-30 19:37
Closing this issue because the code necessary to reproduce the bug has need been included. Please re-open this issue with all the code necessary to reproduce the issue.

**Closed by derekmauro** 2021-08-30 19:37 UTC
Labels: bug

**Comment by davidmerwin** [comment] 2021-08-30 19:39
🌹
________________________________
