### ISSUE TITLE
Compiler emits warning on MOCK_METHOD missing argument to '...' parameter of variadic macro

### ISSUE THREAD

**Issue by keithmendozasr** [google/googletest#2650] opened 2019-12-31 05:50 UTC
When compiling with the -pedantic switch the compiler clang++ 11.0.0 emits the following warning on all calls to MOCK_METHOD:
```
warning: must specify at least one argument for '...' parameter of variadic macro [-Wgnu-zero-variadic-macro-arguments]
    MOCK_METHOD(int, select,
    ^
/Users/kmendoza/rv6_mount/tlslookieloo/googletest/googlemock/include/gmock/gmock-function-mocker.h:50:3: note: expanded from macro 'MOCK_METHOD'
  GMOCK_PP_VARIADIC_CALL(GMOCK_INTERNAL_MOCK_METHOD_ARG_, __VA_ARGS__)
  ^
/Users/kmendoza/rv6_mount/tlslookieloo/googletest/googlemock/include/gmock/internal/gmock-pp.h:49:7: note: expanded from macro 'GMOCK_PP_VARIADIC_CALL'
      GMOCK_PP_CAT(_Macro, GMOCK_PP_NARG(__VA_ARGS__))(__VA_ARGS__))
      ^
/Users/kmendoza/rv6_mount/tlslookieloo/googletest/googlemock/include/gmock/internal/gmock-pp.h:5:30: note: expanded from macro 'GMOCK_PP_CAT'
#define GMOCK_PP_CAT(_1, _2) GMOCK_PP_INTERNAL_CAT(_1, _2)
                             ^
note: (skipping 5 expansions in backtrace; use -fmacro-backtrace-limit=0 to see all)
/Users/kmendoza/rv6_mount/tlslookieloo/googletest/googlemock/include/gmock/internal/gmock-pp.h:103:15: note: expanded from macro 'GMOCK_PP_NARG0'
  GMOCK_PP_IF(GMOCK_PP_IS_EMPTY(__VA_ARGS__), 0, GMOCK_PP_NARG(__VA_ARGS__))
              ^
/Users/kmendoza/rv6_mount/tlslookieloo/googletest/googlemock/include/gmock/internal/gmock-pp.h:80:30: note: expanded from macro 'GMOCK_PP_IS_EMPTY'
  GMOCK_PP_INTERNAL_IS_EMPTY(GMOCK_PP_HAS_COMMA(__VA_ARGS__),                \
                             ^
/Users/kmendoza/rv6_mount/tlslookieloo/googletest/googlemock/include/gmock/internal/gmock-pp.h:37:64: note: expanded from macro 'GMOCK_PP_HAS_COMMA'
      (__VA_ARGS__, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0))
                                                               ^
/Users/kmendoza/rv6_mount/tlslookieloo/googletest/googlemock/include/gmock/internal/gmock-pp.h:159:9: note: macro 'GMOCK_PP_INTERNAL_INTERNAL_16TH' defined here
#define GMOCK_PP_INTERNAL_INTERNAL_16TH(_1, _2, _3, _4, _5, _6, _7, _8, _9, \
```

g++ 8 on Linux emits the following warning on the same lines:
```
warning: ISO C++11 requires at least one argument for the "..." in a variadic macro
```

The warnings are not emitted when the -pedantic switch is not used when compiling.

**Comment by DanRStevens** [comment] 2020-01-06 22:47
I'm also seeing this warning using:
`clang++-6.0`, `clang++-7`, `clang++-8`, `clang++-9`, and `clang-10`

The warning is only shown when the compiled is passed one of the following:
- `-Wpedantic`
- `-Wgnu-zero-variadic-macro-arguments`

----

I was not able to reproduce a warning with GCC. I tested using `-Wpedantic` with:
`g++-7` (7.4.0), or `g++-8` (8.3.0)

GCC (8.3.0) does not recognize the `-Wgnu-zero-variadic-macro-arguments` option.

----

The following StackOverflow question may have some relevant details:
[Variadic macro with no arguments for its variadic parameter](https://stackoverflow.com/questions/16767901/variadic-macro-with-no-arguments-for-its-variadic-parameter)

**Comment by offa** [comment] 2020-02-23 12:55
Same here using clang 5 - 9 (see #2719).

**Comment by Kangz** [comment] 2020-05-11 10:26
Fixed by https://github.com/google/googletest/commit/a09ea700d32bab83325aff9ff34d0582e50e3997, can you close the issue?

**Comment by offa** [comment] 2020-05-11 11:27
This commit works for me (clang 5 - 10).

**Closed** 2020-08-11 15:16 UTC
