### ISSUE TITLE
Compilations failing on ARM64 / Ubuntu 18.04

### ISSUE THREAD

**Issue by pablogh-2000** [google/googletest#3487] opened 2021-07-14 14:52 UTC
**Describe the bug**

Compilation of google benchmark failed due to google test with the following error:

```
[  2%] Building CXX object src/CMakeFiles/benchmark.dir/benchmark.cc.o
In file included from /opt/development/thirdparties/benchmark/googletest/googletest/include/gtest/gtest-death-test.h:41:0,
                 from /opt/development/thirdparties/benchmark/googletest/googletest/include/gtest/gtest.h:64,
                 from /opt/development/thirdparties/benchmark/googletest/googletest/src/gtest-all.cc:38:
/opt/development/thirdparties/benchmark/googletest/googletest/include/gtest/internal/gtest-death-test-internal.h:45:47: error: extra ';' [-Wpedantic]
 GTEST_DECLARE_string_(internal_run_death_test);
                                               ^
In file included from /opt/development/thirdparties/benchmark/googletest/googletest/include/gtest/gtest.h:64:0,
                 from /opt/development/thirdparties/benchmark/googletest/googletest/src/gtest-all.cc:38:
/opt/development/thirdparties/benchmark/googletest/googletest/include/gtest/gtest-death-test.h:48:40: error: extra ';' [-Wpedantic]
 GTEST_DECLARE_string_(death_test_style);
                                        ^
In file included from /opt/development/thirdparties/benchmark/googletest/googletest/src/gtest-all.cc:38:0:
/opt/development/thirdparties/benchmark/googletest/googletest/include/gtest/gtest.h:79:45: error: extra ';' [-Wpedantic]
 GTEST_DECLARE_bool_(also_run_disabled_tests);
                                             ^
/opt/development/thirdparties/benchmark/googletest/googletest/include/gtest/gtest.h:82:38: error: extra ';' [-Wpedantic]
 GTEST_DECLARE_bool_(break_on_failure);
                                      ^
/opt/development/thirdparties/benchmark/googletest/googletest/include/gtest/gtest.h:86:38: error: extra ';' [-Wpedantic]
 GTEST_DECLARE_bool_(catch_exceptions);
                                      ^
/opt/development/thirdparties/benchmark/googletest/googletest/include/gtest/gtest.h:91:29: error: extra ';' [-Wpedantic]
 GTEST_DECLARE_string_(color);

```

**Steps to reproduce the bug**

Follow the building instructions of google benchmarks on ubuntu 18.04 ARM64

**Does the bug persist in the most recent commit?**

When rolling back the last commit of 30 June 2021, it works fine. It is related to the recent commits.

**What operating system and version are you using?**

Ubuntu 18.04 on ARM64

**What compiler and version are you using?**

gcc 7.5.0

**What build system are you using?**

cmake and make

**Additional context**
 
Inside docker container.

**Comment by derekmauro** [comment] 2021-07-19 19:41
Duplicate of #3491

**Closed by derekmauro** 2021-07-19 19:41 UTC
Labels: bug
