### ISSUE TITLE
no member named 'tuple' in namespace 'testing'

### ISSUE THREAD

**Issue by lawben** [google/googletest#1519] opened 2018-03-27 21:19 UTC
On my OSX 10.13.3 with AppleClang 9.0.0.9000039 I cannot build the current master. I get the following error:

```
Users/law/repos/googletest/googlemock/include/gmock/internal/gmock-generated-internal-utils.h:72:33: error:
      no member named 'tuple' in namespace 'testing'
struct MatcherTuple< ::testing::tuple<> > {
                     ~~~~~~~~~~~^
/Users/law/repos/googletest/googlemock/include/gmock/internal/gmock-generated-internal-utils.h:72:39: error:
      expected expression
struct MatcherTuple< ::testing::tuple<> > {
                                      ^
/Users/law/repos/googletest/googlemock/include/gmock/internal/gmock-generated-internal-utils.h:77:33: error:
      no member named 'tuple' in namespace 'testing'
struct MatcherTuple< ::testing::tuple<A1> > {
                     ~~~~~~~~~~~^
/Users/law/repos/googletest/googlemock/include/gmock/internal/gmock-generated-internal-utils.h:77:39: error:
      'A1' does not refer to a value
struct MatcherTuple< ::testing::tuple<A1> > {
                                      ^
/Users/law/repos/googletest/googlemock/include/gmock/internal/gmock-generated-internal-utils.h:76:20: note:
      declared here
template <typename A1>
                   ^
/Users/law/repos/googletest/googlemock/include/gmock/internal/gmock-generated-internal-utils.h:82:33: error:
      no member named 'tuple' in namespace 'testing'
struct MatcherTuple< ::testing::tuple<A1, A2> > {
                     ~~~~~~~~~~~^
/Users/law/repos/googletest/googlemock/include/gmock/internal/gmock-generated-internal-utils.h:82:39: error:
      'A1' does not refer to a value
struct MatcherTuple< ::testing::tuple<A1, A2> > {
                                      ^
/Users/law/repos/googletest/googlemock/include/gmock/internal/gmock-generated-internal-utils.h:81:20: note:
      declared here
template <typename A1, typename A2>
                   ^
/Users/law/repos/googletest/googlemock/include/gmock/internal/gmock-generated-internal-utils.h:87:33: error:
      no member named 'tuple' in namespace 'testing'
struct MatcherTuple< ::testing::tuple<A1, A2, A3> > {
                     ~~~~~~~~~~~^
/Users/law/repos/googletest/googlemock/include/gmock/internal/gmock-generated-internal-utils.h:87:39: error:
      'A1' does not refer to a value
struct MatcherTuple< ::testing::tuple<A1, A2, A3> > {
                                      ^
/Users/law/repos/googletest/googlemock/include/gmock/internal/gmock-generated-internal-utils.h:86:20: note:
      declared here
template <typename A1, typename A2, typename A3>
                   ^
/Users/law/repos/googletest/googlemock/include/gmock/internal/gmock-generated-internal-utils.h:92:33: error:
      no member named 'tuple' in namespace 'testing'
struct MatcherTuple< ::testing::tuple<A1, A2, A3, A4> > {
                     ~~~~~~~~~~~^
/Users/law/repos/googletest/googlemock/include/gmock/internal/gmock-generated-internal-utils.h:92:39: error:
      'A1' does not refer to a value
struct MatcherTuple< ::testing::tuple<A1, A2, A3, A4> > {
                                      ^
/Users/law/repos/googletest/googlemock/include/gmock/internal/gmock-generated-internal-utils.h:91:20: note:
      declared here
template <typename A1, typename A2, typename A3, typename A4>
                   ^
/Users/law/repos/googletest/googlemock/include/gmock/internal/gmock-generated-internal-utils.h:98:33: error:
      no member named 'tuple' in namespace 'testing'
struct MatcherTuple< ::testing::tuple<A1, A2, A3, A4, A5> > {
                     ~~~~~~~~~~~^
/Users/law/repos/googletest/googlemock/include/gmock/internal/gmock-generated-internal-utils.h:98:39: error:
      'A1' does not refer to a value
struct MatcherTuple< ::testing::tuple<A1, A2, A3, A4, A5> > {
                                      ^
/Users/law/repos/googletest/googlemock/include/gmock/internal/gmock-generated-internal-utils.h:97:20: note:
      declared here
template <typename A1, typename A2, typename A3, typename A4, typename A5>
                   ^
/Users/law/repos/googletest/googlemock/include/gmock/internal/gmock-generated-internal-utils.h:106:33: error:
      no member named 'tuple' in namespace 'testing'
struct MatcherTuple< ::testing::tuple<A1, A2, A3, A4, A5, A6> > {
                     ~~~~~~~~~~~^
/Users/law/repos/googletest/googlemock/include/gmock/internal/gmock-generated-internal-utils.h:106:39: error:
      'A1' does not refer to a value
struct MatcherTuple< ::testing::tuple<A1, A2, A3, A4, A5, A6> > {
                                      ^
/Users/law/repos/googletest/googlemock/include/gmock/internal/gmock-generated-internal-utils.h:104:20: note:
      declared here
template <typename A1, typename A2, typename A3, typename A4, typename A5,
                   ^
/Users/law/repos/googletest/googlemock/include/gmock/internal/gmock-generated-internal-utils.h:114:33: error:
      no member named 'tuple' in namespace 'testing'
struct MatcherTuple< ::testing::tuple<A1, A2, A3, A4, A5, A6, A7> > {
                     ~~~~~~~~~~~^
/Users/law/repos/googletest/googlemock/include/gmock/internal/gmock-generated-internal-utils.h:114:39: error:
      'A1' does not refer to a value
struct MatcherTuple< ::testing::tuple<A1, A2, A3, A4, A5, A6, A7> > {
                                      ^
/Users/law/repos/googletest/googlemock/include/gmock/internal/gmock-generated-internal-utils.h:112:20: note:
      declared here
template <typename A1, typename A2, typename A3, typename A4, typename A5,
                   ^
/Users/law/repos/googletest/googlemock/include/gmock/internal/gmock-generated-internal-utils.h:122:33: error:
      no member named 'tuple' in namespace 'testing'
struct MatcherTuple< ::testing::tuple<A1, A2, A3, A4, A5, A6, A7, A8> > {
                     ~~~~~~~~~~~^
/Users/law/repos/googletest/googlemock/include/gmock/internal/gmock-generated-internal-utils.h:122:39: error:
      'A1' does not refer to a value
struct MatcherTuple< ::testing::tuple<A1, A2, A3, A4, A5, A6, A7, A8> > {
                                      ^
/Users/law/repos/googletest/googlemock/include/gmock/internal/gmock-generated-internal-utils.h:120:20: note:
      declared here
template <typename A1, typename A2, typename A3, typename A4, typename A5,
                   ^
/Users/law/repos/googletest/googlemock/include/gmock/internal/gmock-generated-internal-utils.h:130:33: error:
      no member named 'tuple' in namespace 'testing'
struct MatcherTuple< ::testing::tuple<A1, A2, A3, A4, A5, A6, A7, A8, A9> > {
                     ~~~~~~~~~~~^
fatal error: too many errors emitted, stopping now [-ferror-limit=]
20 errors generated.
make[2]: *** [googlemock/CMakeFiles/gmock.dir/src/gmock-all.cc.o] Error 1
make[1]: *** [googlemock/CMakeFiles/gmock.dir/all] Error 2
make: *** [all] Error 2
```

This worked about 3 hours ago, so I am assuming it has something to do with merging #1518. 

The command when running `make -j VERBOSE=1` that shows this error is:

```
/Library/Developer/CommandLineTools/usr/bin/c++   -I/Users/law/repos/googletest/googlemock/include -I/Users/law/repos/googletest/googlemock -isystem /Users/law/repos/googletest/googletest/include -I/Users/law/repos/googletest/googletest  -DGTEST_HAS_PTHREAD=1   -o CMakeFiles/gmock.dir/src/gmock-all.cc.o -c /Users/law/repos/googletest/googlemock/src/gmock-all.cc
```

**Comment by lawben** [comment] 2018-03-27 21:28
When going back 2 comits to `cafa9e52285d743d1394900fa95662950f712a72` (Merge pull request #1515 from gennadiycivil/master) I can build this. So the error must lie in the latest merge.

**Comment by jonbronson** [comment] 2018-03-27 23:50
I'm encountering the same issue.

[ 37%] Building CXX object googlemock/CMakeFiles/gmock.dir/src/gmock-all.cc.o
In file included from /build/externals/googletest/src/googletest/googlemock/src/gmock-all.cc:40:
In file included from /build/externals/googletest/src/googletest/googlemock/include/gmock/gmock.h:58:
In file included from /build/externals/googletest/src/googletest/googlemock/include/gmock/gmock-actions.h:46:
In file included from /build/externals/googletest/src/googletest/googlemock/include/gmock/internal/gmock-internal-utils.h:44:
/build/externals/googletest/src/googletest/googlemock/include/gmock/internal/gmock-generated-internal-utils.h:72:33: error: no member named 'tuple' in
      namespace 'testing'
struct MatcherTuple< ::testing::tuple<> > {
                     ~~~~~~~~~~~^
/build/externals/googletest/src/googletest/googlemock/include/gmock/internal/gmock-generated-internal-utils.h:72:39: error: expected expression
struct MatcherTuple< ::testing::tuple<> > {
                                      ^
/build/externals/googletest/src/googletest/googlemock/include/gmock/internal/gmock-generated-internal-utils.h:77:33: error: no member named 'tuple' in
      namespace 'testing'
struct MatcherTuple< ::testing::tuple<A1> > {
                     ~~~~~~~~~~~^
/build/externals/googletest/src/googletest/googlemock/include/gmock/internal/gmock-generated-internal-utils.h:77:39: error: 'A1' does not refer to a value
struct MatcherTuple< ::testing::tuple<A1> > {
                                      ^
/build/externals/googletest/src/googletest/googlemock/include/gmock/internal/gmock-generated-internal-utils.h:76:20: note: declared here
template <typename A1>

**Comment by psalaberria002** [comment] 2018-03-28 11:10
Same error here.
```
 no member named 'tuple' in namespace 'testing'
```

**Comment by magnanim** [comment] 2018-03-28 11:17
Same here :)

**Comment by pomidorov** [comment] 2018-03-28 12:52
Same for me

**Comment by jonbronson** [comment] 2018-03-30 19:41
Appears to be fixed after KhronosGroup/SPIRV-Tools#1441 revert.

**Comment by leahecole** [comment] 2018-10-10 22:29
Still having this problem - any other folks having this still?

**Comment by gennadiycivil** [comment] 2018-10-11 17:39
::testing::tuple has been removed on purpose in favor of standard std::tuple. This is not a regression

**Comment by leahecole** [comment] 2018-10-12 18:35
@gennadiycivil - thanks for the reply - I actually made an error reading this - I am seeing no member named 'tuple' in namespace 'std', not in namespace 'testing'. I'll make sure my team working on this is using C++ 11.

**Comment by gennadiycivil** [comment] 2018-10-26 18:54
Great to hear , thank you. Closing

**Closed by gennadiycivil** 2018-10-26 18:54 UTC
Labels: GC Attention Set

**Comment by eddyekofo94** [comment] 2019-08-22 03:51
if using CMake `set(CMAKE_CXX_STANDARD 17)` # or 11 as you please

**Comment by wgroeneveld** [comment] 2019-11-08 14:12
> if using CMake `set(CMAKE_CXX_STANDARD 17)` # or 11 as you please

Thank you, why isn't this in the CMakeLists.txt on the master branch?

**Comment by MarkOates** [comment] 2020-02-29 22:41
I was able to solve this by including `-DCMAKE_CXX_STANDARD=17` during the `cmake` step. Complete build steps being:

```
git clone https://github.com/google/googletest
cd googletest
mkdir build
cd build
cmake .. -DCMAKE_CXX_STANDARD=17
make
make install
```

**Comment by ZaccurLi** [comment] 2020-03-04 13:30
> I was able to solve this by including `-DCMAKE_CXX_STANDARD=17` during the `cmake` step.
> 
> The complete build steps are:
> 
> ```
> git clone https://github.com/google/googletest
> cd googletest
> mkdir build
> cd build
> cmake .. -DCMAKE_CXX_STANDARD=17
> make
> make install
> ```
> 
> I do feel that this extra flag should not need to be added by the builder (and should be specified elsewhere), or should be documented somewhere in the build instructions.

I think so
it took me a long time to  find the solution,
your comment helps me a lot
thanks

**Comment by BorisMansencal** [comment] 2020-03-25 15:18
I had the same error with current git head : no member named 'tuple' in namespace 'std'
(with clang-1100.0.33.1 on macOS 10.14.6)
'tuple' and 'make_tuple' were introduced in the 'std' namespace with C++11. Thus the code must be compiled with at least the C++11 standard.
One way to compile with C++11 with clang is for example to change line 85 of googletest/cmake/internal_utils.cmake to:
```
set(cxx_base_flags "-Wall -Wshadow -Werror -Wconversion -std=c++11")
```

**Comment by tobegit3hub** [comment] 2020-03-31 14:46
Adding `set(CMAKE_CXX_STANDARD 11)` in `CMakeLists.txt` works for me with `cmake` .

**Comment by OlivierLDff** [comment] 2020-04-11 14:24
Why not use modern cmake fnyuction `target_compile_features`
In function `cxx_library_with_type` in `googletest/cmake/internal_utils.cmake` :
`target_compile_features(${name} PUBLIC cxx_std_11)`
Of course this won't fix the problem for people using cmake version lower than 3.0
