### ISSUE TITLE
linux make[1]: *** [googletest/CMakeFiles/gtest.dir/all] Error 2 

### ISSUE THREAD

**Issue by ZJolin** [google/googletest#3640] opened 2021-11-02 07:52 UTC
**Describe the bug**
I'm trying to build gtest and gmock (1.11.0) in linux.
git clone https://github.com/google/googletest.git -b release-1.11.0
I have upgraded GCC to 11.2.0, and the problem still occurred.

**Steps to reproduce the bug**

/root/source/googletest/googletest/src/gtest-matchers.cc:55:61: required from here
/root/source/googletest/googletest/include/gtest/gtest-matchers.h:416:3: error: body of constexpr function ‘static constexpr bool testing::internal::MatcherBase::IsInlined() [with M = testing::internal::EqMatcher<std::basic_string >; T = std::basic_string]’ not a return-statement
}
^
/root/source/googletest/googletest/include/gtest/gtest-matchers.h: In instantiation of ‘void testing::internal::MatcherBase::Init(M&&) [with M = testing::internal::EqMatcher<std::basic_string >; T = std::basic_string]’:
/root/source/googletest/googletest/include/gtest/gtest-matchers.h:298:28: required from ‘testing::internal::MatcherBase::MatcherBase(M&&) [with M = testing::internal::EqMatcher<std::basic_string >; = void; T = std::basic_string]’
/root/source/googletest/googletest/include/gtest/gtest-matchers.h:545:62: required from ‘testing::Matcher<std::basic_string >::Matcher(M&&) [with M = testing::internal::EqMatcher<std::basic_string >; = void]’
/root/source/googletest/googletest/src/gtest-matchers.cc:55:61: required from here
/root/source/googletest/googletest/include/gtest/gtest-matchers.h:418:58: error: ‘static constexpr bool testing::internal::MatcherBase::IsInlined() [with M = testing::internal::EqMatcher<std::basic_string >; T = std::basic_string]’ called in a constant expression
template <typename M, bool = MatcherBase::IsInlined()>
^
/root/source/googletest/googletest/include/gtest/gtest-matchers.h:412:25: note: ‘static constexpr bool testing::internal::MatcherBase::IsInlined() [with M = testing::internal::EqMatcher<std::basic_string >; T = std::basic_string]’ is not usable as a constexpr function because:
static constexpr bool IsInlined() {
^
/root/source/googletest/googletest/include/gtest/gtest-matchers.h:463:35: note: in template argument for type ‘bool’
using Policy = ValuePolicy;
^
make[2]: *** [googletest/CMakeFiles/gtest.dir/src/gtest-all.cc.o] Error 1
make[1]: *** [googletest/CMakeFiles/gtest.dir/all] Error 2
make: *** [all] Error 2
[root@VM-155-224-centos ~/source/googletest/build]# gcc --version
gcc (GCC) 11.2.0
Copyright (C) 2021 Free Software Foundation, Inc.
This is free software; see the source for copying conditions. There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

**What operating system and version are you using?**

Linux VM-155-224-centos 5.4.119-1-tlinux4-0005 #1 SMP Thu Jul 8 11:20:55 CST 2021 x86_64 x86_64 x86_64 GNU/Linux

**What compiler and version are you using?**

Using built-in specs.
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/usr/local/libexec/gcc/x86_64-pc-linux-gnu/11.2.0/lto-wrapper
Target: x86_64-pc-linux-gnu
Configured with: ./configure -enable-checking=release -enable-languages=c,c++ -disable-multilib
Thread model: posix
Supported LTO compression algorithms: zlib
gcc version 11.2.0 (GCC) 

**What build system are you using?**

cmake version 3.20.0

**Comment by anthonygraca** [comment] 2021-11-02 22:06
Just for clarification, are you using CentOS 5.4 or is your Linux kernel version 5.4?

**Comment by ZJolin** [comment] 2021-11-03 02:39
> Just for clarification, are you using CentOS 5.4 or is your Linux kernel version 5.4?

Linux VM-155-224-centos 5.4.119-1-tlinux4-0005 #1 SMP Thu Jul 8 11:20:55 CST 2021 x86_64 x86_64 x86_64 GNU/Linux

**Comment by derekmauro** [comment] 2021-11-08 20:39
Duplicate of #3476

**Closed by derekmauro** 2021-11-08 20:39 UTC
Labels: bug
