### ISSUE TITLE
FR: Customize failure log line number for EXPECT_CALL

### ISSUE THREAD

**Issue by pavolmarko** [google/googletest#2732] opened 2020-02-27 09:27 UTC
We tend to use this pattern in a few tests to avoid copy&pasting:
```
void SetupComplexExpectation() {
  EXPECT_CALL(...).WillRepeatedly(...);
}
// .. Other functions such as SetupOtherComplexExpectation

TEST_F(TestFxiture, Test1) {
  SetupComplexExpectation();
  DoSomething();
}

TEST_F(TestFxiture, Test2) {
  SetupComplexExpectation();
  DoSomethingElse();
}
```

It works fine, but the line numbers printed when the expectation fails are from the SetupComplexExpectation() function.

We would like to be able to do something like tihs:
```
void SetupComplexExpectation(const gmock::Location& location) {
  EXPECT_CALL(...).WithCustomLogLocation(location).WillRepeatedly(...);
}
// .. Other functions such as SetupOtherComplexExpectation

TEST_F(TestFxiture, Test1) {
  SetupComplexExpectation(GMOCK_FROM_HERE);
  DoSomething();
}

TEST_F(TestFxiture, Test2) {
  SetupComplexExpectation(GMOCK_FROM_HERE);
  DoSomethingElse();
}
```

Similar to the chromium base::Location pattern ( https://cs.chromium.org/chromium/src/base/location.h?type=cs&q=base::location&sq=package:chromium&g=0&l=36 ).

The WithCustomLocation() function would customize the ExpectationBase's line_ and file_ members accordingly.

If this is something that the googletest team considers a good API idea, we would send a CL.

**Comment by asoffer** [comment] 2020-03-03 15:02
Duplicate of #2646

**Closed by asoffer** 2020-03-03 15:02 UTC
