### ISSUE TITLE
[FR]: `FetchContetn` on `googletest` subfolder

### ISSUE THREAD

**Issue by LecrisUT** [google/googletest#4467] opened 2024-02-15 18:22 UTC
### Does the feature exist in the most recent commit?

No

### Why do we need this feature?

Avoid building with `gmock`

### Describe the proposal.

Let's say we want to consume gtest as:
```cmake
FetchContent_Declare(GTest
		GIT_REPOSITORY https://github.com/google/googletest
		GIT_TAG v1.14.0
		SOURCE_SUBDIR googletest
		FIND_PACKAGE_ARGS CONFIG
)
```

This fails because `GOOGLETEST_VERSION` is only defined in top level cmakelists. This means the that the `gtest` is not independently buildable

### Is the feature specific to an operating system, compiler, or build system version?

Build system: CMake + FetchContent

**Comment by derekmauro** [comment] 2024-02-26 20:28
Duplicate of #4309.

**Closed by derekmauro** 2024-02-26 20:28 UTC
Labels: enhancement
