### ISSUE TITLE
Identifier "EXPECT_THAT" is undefined

### ISSUE THREAD

**Issue by llodds** [google/googletest#3830] opened 2022-05-12 00:21 UTC
What could be reason for the following issues? 

"EXPECT_EQ" works but the following identifiers don't:

> identifier "EXPECT_THAT" is undefined
> identifier "ElementsAre" is undefined

Thanks.

**Comment by dinord** [comment] 2022-05-16 19:59
That typically happens when you either do not #include the necessary headers, or you do include them, but do not compile the program correctly (e.g. do not link the required libraries).  
Check out our [Bazel](https://google.github.io/googletest/quickstart-bazel.html) or [CMake](https://google.github.io/googletest/quickstart-cmake.html) quickstarts for examples of how to use GoogleTest.

I'm closing this issue, since there is no information that would help us reproduce it. If you have a specific example, please open a new issue using the "Bug report" template, and make sure to provide the details requested in the template.

**Closed by dinord** 2022-05-16 19:59 UTC

**Comment by Rahlir** [comment] 2022-10-18 17:57
I ran into the same issue. This was resolved by adding `gmock` as a library to link with my test target in `CMakeLists.txt`. @dinord You referenced here the CMake quickstart but the confusion for me was exactly by following the quickstart: nowhere in the quickstart or in the tutorial is it mentioned that to allow a user to use any functionalities from Gmock you need to add it as an additional library in cmake. While this might be obvious to long time users of googletest, I believe it is far from obvious for new users: the docs act as if gmock is part of googletest. I would suggest adding the info re. need for additional cmake library link somewhere in the docs: either to the building quickstart or to the mocking basic info: again, it's only mentioned that you should include `"gmock.h"`, which just adds to the confusion since that does not work unless you change the cmake setup.
