### ISSUE TITLE
Treat unexpected exit as error

### ISSUE THREAD

**Issue by JojOatXGME** [google/googletest#1146] opened 2017-07-09 12:23 UTC
I have a function that exits the application when the arguments meet specific conditions. I can use *Death Tests* to verify that the application is going down when required. However, I have not found a feature to check that a statement is not dying when it should not. Currently, the test application just stopes execution in this case. Possibly with exit code 0. Therefore, I would like to have a feature to verify that a statement does not die.

I would even prefer to start every test in a *Death Test like* environment when supported by the platform. Then, the test application can write proper error messages and contine even after a test has crashed or has called `exit` for some reason. Since the *Death Test like* environment isn't terminated on successful tests, it can be reused for further tests. This way, the overhead should not be a problem.

Are there any concerns or additions? I am just afraid that such feature would require some major changes in the implementation.

**Comment by gennadiycivil** [comment] 2018-10-08 21:29
@JojOatXGME I suggest actually creating a PR so we can take a look

**Comment by jadoro** [comment] 2019-05-16 07:30
I'm having the same problems as @JojOatXGME and I'm not sure why this issue has been closed. I'm trying to test code that makes use of a plain C library handling errors by printing to stdout and exiting.
This issue renders `gtest` more or less unusable in the described scenario, since failing tests lead to crashing test runners and no generated results.

Consider the following snippet:

```cpp
#include "gtest/gtest.h"

TEST(TestSuiteDeathTest, ExitTestShouldNotFail) {
    ASSERT_DEATH(exit(1), ".*");
}

TEST(TestSuiteDeathTest, ExitTestShouldFail) {
    exit(1);
}
```

I would assume that `ExitTestShouldFail` will be reported as failure and (if requested) an xml file is generated.

Unfortunately, `gtest` exits with the test and does not catch the unexpected `exit()` call:

```
[==========] Running 2 tests from 1 test case.
[----------] Global test environment set-up.
[----------] 2 tests from TestSuiteDeathTest
[ RUN      ] TestSuiteDeathTest.ExitTestShouldNotFail
[       OK ] TestSuiteDeathTest.ExitTestShouldNotFail (4 ms)
[ RUN      ] TestSuiteDeathTest.ExitTestShouldFail
```

**Comment by JojOatXGME** [comment] 2019-05-16 19:08
I guess the ticket has been closed because it was inactive for over a year. I looked at the code for a few hours some time ago. However, since I'm not familiar with the code base I did not come very far. I would still like to see a solution but I have other priorities since I'm not using GTest very much.

Also note that there seem to be a workaround. You can set the environment variable `TEST_PREMATURE_EXIT_FILE` to an absolute path. GTest will create a file under the given path and delete it when it is complete. If the file still exists after the executable has exited, the last test has failed.

**Comment by gennadiycivil** [comment] 2019-05-16 19:41
I have been cleaning up older and inactive GitHub googletest issues. You may see an issue "closed" if it appears to be inactive/abandoned 
Thank you

**Comment by jadoro** [comment] 2019-05-17 17:59
> You may see an issue "closed" if it appears to be inactive/abandoned

Thanks for the explanation @gennadiycivil. Since there's activity now and I have provided a minimum working example for reproducing the issue, would you mind reopening it?
I'll be happy to open a new issue with the same topic if you prefer that.

**Comment by gennadiycivil** [comment] 2019-05-17 20:37
I am happy to re-open however just to be absolutely clear, this will not be treated as a priority by the maintainers. 
In other words, the best way to approach this would be to create a proper PR and submit it for consideration.

**Comment by kuzkry** [comment] 2019-11-02 15:52
Hi all! What @JojOatXGME wrote is not actually a workaround, but the expected behaviour. I suppose the reason for this is that such a "hack" will work almost always - definitely more robust than installing custom _atexit_ handlers which are easily skipped (consider stack smashing in an infinite loop) and I've already seen this pattern in different companies.

Comment from [gtest.cc](https://github.com/google/googletest/blob/e8a82dc7ede61c4af3b9d75aa0e953b8cecfc8bb/googletest/src/gtest.cc#L4851):
>   // (...) If the program
>   // somehow exits before this function has a chance to return, the
>   // premature-exit file will be left undeleted, causing a test runner
>   // that understands the premature-exit-file protocol to report the
>   // test as having failed.

In my opinion, this information should actually be described in documentation; currently it isn't.

Anyway, I hope my answer is fine with you. If yes, then please close this issue down.

**Comment by asoffer** [comment] 2020-03-27 20:34
Sorry for the long response time. I don't think we want to support this. The common uses are either with Bazel or CTest, each of which report failures with non-zero exit codes, so the end-results are still the same.

**Closed by asoffer** 2020-03-27 20:34 UTC

**Comment by JojOatXGME** [comment] 2020-03-28 02:56
@asoffer, I'm fine with that. It would be a nice feature, though. I just want to recap that it also was about tests which unexpectedly call `exit(0)`. As far as I know, *CTest* will not detect such failures out of the box. Anyway, documenting `TEST_PREMATURE_EXIT_FILE` will already help there.

**Comment by asoffer** [comment] 2020-04-03 14:54
I understand the concern. Unexpectedly calling exit(0) is a class of issues we do not want to support. exit(0) needs to mean success. A call to exit(0) doesn't have to be problematic in tests or production code. Using the TEST_PREMATURE_EXIT_FILE essentially kicks the can down the road a bit by constructing a different mechanism by which one can report success or failure. In our mind, this adds more complication. Should this work for exit? quick_exit? terminate? abort? Which signals should be handled? Combinations of these? What if we fail to write the file? Or it's cleaned up mid-test? It's not that these questions do not have answers it's that we believe answering them leads to more complication than the facility is worth. We think for understandability it is easiest to have the simple rule: 0 means success. We recognize that this means some code may need to be changed to be testable, but this is already the case with GoogleTest.
